package cn.com.example.test.dao;

import cn.com.example.test.domain.TAddress;

import java.util.List;

public interface TAddressDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int insert(TAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int insertSelective(TAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    TAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAddress record);
    void deleteById(Integer id);
    void updateById(TAddress address);
    TAddress selectAddressById(Integer id);
    Integer setDefault(Integer id);
    Integer setCancel(Integer uid);
    List<TAddress>selectByUid(Integer uid);

}