package cn.com.example.test.dao;

import cn.com.example.test.domain.TDictCities;

import java.util.List;

public interface TDictCitiesDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_cities
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_cities
     *
     * @mbg.generated
     */
    int insert(TDictCities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_cities
     *
     * @mbg.generated
     */
    int insertSelective(TDictCities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_cities
     *
     * @mbg.generated
     */
    TDictCities selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_cities
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDictCities record);
    List<TDictCities> selectCity(String provinceCode);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_cities
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDictCities record);
    String selectCityNameByCode(String cityCode);
}