package cn.com.example.test.dao;

import cn.com.example.test.domain.TDictCities;
import cn.com.example.test.domain.TDictProvinces;

import java.util.List;

public interface TDictProvincesDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_provinces
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);
    List<TDictProvinces>selectProvince();


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_provinces
     *
     * @mbg.generated
     */
    int insert(TDictProvinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_provinces
     *
     * @mbg.generated
     */
    int insertSelective(TDictProvinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_provinces
     *
     * @mbg.generated
     */
    TDictProvinces selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_provinces
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDictProvinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_provinces
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDictProvinces record);
    String selectProvinceNameByCode(String provinceCode);
}