package cn.com.example.test.domain;

import java.util.Date;

public class TAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.recv_name
     *
     * @mbg.generated
     */
    private String recvName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.recv_province
     *
     * @mbg.generated
     */
    private String recvProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.recv_city
     *
     * @mbg.generated
     */
    private String recvCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.recv_area
     *
     * @mbg.generated
     */
    private String recvArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.recv_distric
     *
     * @mbg.generated
     */
    private String recvDistric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.recv_address
     *
     * @mbg.generated
     */
    private String recvAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.recv_phone
     *
     * @mbg.generated
     */
    private String recvPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.recv_tel
     *
     * @mbg.generated
     */
    private String recvTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.recv_zip
     *
     * @mbg.generated
     */
    private String recvZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.recv_tag
     *
     * @mbg.generated
     */
    private String recvTag;
    private Integer isDefault;

    public Integer getIsDefault() {
        return isDefault;
    }

    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.created_user
     *
     * @mbg.generated
     */
    private String createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.modified_user
     *
     * @mbg.generated
     */
    private String modifiedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.id
     *
     * @return the value of t_address.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.id
     *
     * @param id the value for t_address.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.uid
     *
     * @return the value of t_address.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.uid
     *
     * @param uid the value for t_address.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.recv_name
     *
     * @return the value of t_address.recv_name
     *
     * @mbg.generated
     */
    public String getRecvName() {
        return recvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.recv_name
     *
     * @param recvName the value for t_address.recv_name
     *
     * @mbg.generated
     */
    public void setRecvName(String recvName) {
        this.recvName = recvName == null ? null : recvName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.recv_province
     *
     * @return the value of t_address.recv_province
     *
     * @mbg.generated
     */
    public String getRecvProvince() {
        return recvProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.recv_province
     *
     * @param recvProvince the value for t_address.recv_province
     *
     * @mbg.generated
     */
    public void setRecvProvince(String recvProvince) {
        this.recvProvince = recvProvince == null ? null : recvProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.recv_city
     *
     * @return the value of t_address.recv_city
     *
     * @mbg.generated
     */
    public String getRecvCity() {
        return recvCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.recv_city
     *
     * @param recvCity the value for t_address.recv_city
     *
     * @mbg.generated
     */
    public void setRecvCity(String recvCity) {
        this.recvCity = recvCity == null ? null : recvCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.recv_area
     *
     * @return the value of t_address.recv_area
     *
     * @mbg.generated
     */
    public String getRecvArea() {
        return recvArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.recv_area
     *
     * @param recvArea the value for t_address.recv_area
     *
     * @mbg.generated
     */
    public void setRecvArea(String recvArea) {
        this.recvArea = recvArea == null ? null : recvArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.recv_distric
     *
     * @return the value of t_address.recv_distric
     *
     * @mbg.generated
     */
    public String getRecvDistric() {
        return recvDistric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.recv_distric
     *
     * @param recvDistric the value for t_address.recv_distric
     *
     * @mbg.generated
     */
    public void setRecvDistric(String recvDistric) {
        this.recvDistric = recvDistric == null ? null : recvDistric.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.recv_address
     *
     * @return the value of t_address.recv_address
     *
     * @mbg.generated
     */
    public String getRecvAddress() {
        return recvAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.recv_address
     *
     * @param recvAddress the value for t_address.recv_address
     *
     * @mbg.generated
     */
    public void setRecvAddress(String recvAddress) {
        this.recvAddress = recvAddress == null ? null : recvAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.recv_phone
     *
     * @return the value of t_address.recv_phone
     *
     * @mbg.generated
     */
    public String getRecvPhone() {
        return recvPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.recv_phone
     *
     * @param recvPhone the value for t_address.recv_phone
     *
     * @mbg.generated
     */
    public void setRecvPhone(String recvPhone) {
        this.recvPhone = recvPhone == null ? null : recvPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.recv_tel
     *
     * @return the value of t_address.recv_tel
     *
     * @mbg.generated
     */
    public String getRecvTel() {
        return recvTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.recv_tel
     *
     * @param recvTel the value for t_address.recv_tel
     *
     * @mbg.generated
     */
    public void setRecvTel(String recvTel) {
        this.recvTel = recvTel == null ? null : recvTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.recv_zip
     *
     * @return the value of t_address.recv_zip
     *
     * @mbg.generated
     */
    public String getRecvZip() {
        return recvZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.recv_zip
     *
     * @param recvZip the value for t_address.recv_zip
     *
     * @mbg.generated
     */
    public void setRecvZip(String recvZip) {
        this.recvZip = recvZip == null ? null : recvZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.recv_tag
     *
     * @return the value of t_address.recv_tag
     *
     * @mbg.generated
     */
    public String getRecvTag() {
        return recvTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.recv_tag
     *
     * @param recvTag the value for t_address.recv_tag
     *
     * @mbg.generated
     */
    public void setRecvTag(String recvTag) {
        this.recvTag = recvTag == null ? null : recvTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.created_user
     *
     * @return the value of t_address.created_user
     *
     * @mbg.generated
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.created_user
     *
     * @param createdUser the value for t_address.created_user
     *
     * @mbg.generated
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser == null ? null : createdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.created_time
     *
     * @return the value of t_address.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.created_time
     *
     * @param createdTime the value for t_address.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.modified_user
     *
     * @return the value of t_address.modified_user
     *
     * @mbg.generated
     */
    public String getModifiedUser() {
        return modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.modified_user
     *
     * @param modifiedUser the value for t_address.modified_user
     *
     * @mbg.generated
     */
    public void setModifiedUser(String modifiedUser) {
        this.modifiedUser = modifiedUser == null ? null : modifiedUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.modified_time
     *
     * @return the value of t_address.modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.modified_time
     *
     * @param modifiedTime the value for t_address.modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}